{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "GH_SW API",
    "description": "GH_SW API",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },
  "tags": [
    {
      "name": "GH_SW API",
      "description": "Game Hall Seamless Wallet API"
    }
  ],
  "servers": [
    {
      "url": "https://s-ghapi-uat.incash.site",
      "description": "Production server"
    }
  ],
  "paths": {
    "/api/CreateMember": {
      "post": {
        "tags":["/api"],
        "summary": "Summary of Create Member:...",
        "description": "Discription of Create Member:...",
        "requestBody": {
          "description": "Parameter",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref":"#/components/schemas/CreateMemberParams"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Discription of Create Member response:...",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CommonResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/launchGame": {
      "post": {
        "tags":["/api"],
        "summary": "Summary of Launch Game:...",
        "description": "Discription of Launch Game:...",
        "requestBody": {
          "description": "Description of parameters:...",
          "required": true,
          "content": {
            "application/json": {
              "schema":{
                "$ref":"#/components/schemas/LaunchGameParams"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Discription of Launch Game response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CommonResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/GetTransResult": {
      "post": {
        "tags":["/api"],
        "summary": "Summary of GetTransResult:...",
        "description": "Discription of GetTransResult:...",
        "requestBody": {
          "description": "Description of request body...",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref":"#/components/schemas/GetTransResultParams"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Discription of GetTransResul response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CommonResponse"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "CommonResponse": {
        "properties": {
          "ReturnCode": {
            "type": "string"
          },
          "Description": {
            "type": "string"
          },
          "datetime": {
            "type": "string"
          },
          "ErrMsg": {
            "type": "string"
          }
        },
        "example": {
          "ReturnCode": "0",
          "Description":"Success",
          "datetime":"",
          "ErrMsg":""
        }
      },
      "CreateMemberParams":{
          "properties": {
            "privateKey": {
              "type": "string"
            },
            "username": {
              "type": "string"
            },
            "currency": {
              "type": "string"
            },
            "language": {
              "type": "string"
            }
          },
          "example": {
            "privateKey": "ls2nsCaUdQs5VqIXlcIguj54afhaA6VQv/26PDpiffBbG5K+IyaZrrsrBrK2pkc1f3IMeKLW6PqdprBMHMqSTQ7gcmlcx7jZMxmyeTTBXRqcNhXrxoYZ41UTA7QmwDh5p044MJHrfmmYt5M/aPAZO0hOolQ7uKNidm/xlnFgBiE=",
            "username": "test01",
            "currency": "IDR",
            "language": "en"
          }
      },
      "LaunchGameParams":{
        "properties": {
          "privateKey": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "platform": {
            "type": "string"
          },
          "gameType": {
            "type": "string"
          },
          "gameCode": {
            "type": "string"
          },
          "isMobileLogin": {
            "type": "boolean"
          },
          "GameCurCode": {
            "type": "string"
          }
        },
        "example": {
          "privateKey": "ls2nsCaUdQs5VqIXlcIguj54afhaA6VQv/26PDpiffBbG5K+IyaZrrsrBrK2pkc1f3IMeKLW6PqdprBMHMqSTQ7gcmlcx7jZMxmyeTTBXRqcNhXrxoYZ41UTA7QmwDh5p044MJHrfmmYt5M/aPAZO0hOolQ7uKNidm/xlnFgBiE=",
          "username":"test01",
          "platform":"FC",
          "gameType":"SLOT",
          "gameCode": "FC-SLOT-002",
          "isMobileLogin":false,
          "GameCurCode":"IDR2"
        }
      },
      "GetTransResultParams":{
        "properties": {
          "privateKey": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "TransId": {
            "type": "string"
          }
        },
        "example": {
          "privateKey": "ls2nsCaUdQs5VqIXlcIguj54afhaA6VQv/26PDpiffBbG5K+IyaZrrsrBrK2pkc1f3IMeKLW6PqdprBMHMqSTQ7gcmlcx7jZMxmyeTTBXRqcNhXrxoYZ41UTA7QmwDh5p044MJHrfmmYt5M/aPAZO0hOolQ7uKNidm/xlnFgBiE=",
          "username":"test01",
          "TransId":"1397"
        }
      }   
    }
  }
}
